---
# tasks file for awx
#- name: This command will change the working directory to somedir/.
 # shell:
  #  cmd:  yum install epel-release -y
   #     #  yum install git gcc gcc-c++ nodejs gettext device-mapper-persistent-data lvm2 bzip2 python3-pip

 - name: Installing AWX dependencies
   package:
     name: "{{ item }}"
     state: present
   with_items: "{{ awx_package_dependencies }}"  

 - name: Clone AWX into configured directory
   git:
     repo: "{{ awx_repo }}"
     dest: "{{ awx_repo_dir }}"
     version: "{{ awx_version }}"
     update: "{{ awx_keep_updated }}"
     force: true
     accept_hostkey: true

#- include: awx-install-playbook.yml                    
 # when: awx_run_install_playbook
